### PR TITLE
Knet-1.4.0 compatibility fixes

### PR DESCRIPTION
**Pull request by denizyuret**
I fixed a few things to ensure compatibility with Knet-1.4.0. Do you want to keep KnetLayers separate or make it part of the standard Knet distro as Knet.Layers20 submodule, let me know.

### CODE REVIEW

**Comment by ekinakyurek** [comment]
Thanks @denizyuret. I think they are pretty standard layers, so it should be coming default with Knet either inside or a requirement handled by Project.toml. For seperate packages scenario, we can manage versions together, we can move it to KnetML, etc. The advantage here is that people would be more welcome to contribute to layers. 

However, if you think it's hard to adjust version control for separate packages, I can copy these files into Knet the and you can make it work as submodule. 

So, let me know your decision.

**Comment by denizyuret** [comment]
I can see pros and cons of both approaches. Right now I am leaning towards a Knet.Layers20 submodule but not very strongly. That way it can be tested within Knet and never fall out of sync. Hopefully the submodule structure will make it semi-independent and contributors will be less likely to be intimidated.

I noticed that you have also written code for things other than layers, loading data, models etc. These should ideally go into different submodules if we merge. I am planning to create Knet.Data and Knet.Models submodules, load standard datasets and precompiled models using Artifacts. I will work on the HuggingFace models and standard CV models first to get things started. The other option is to delay this decision until the new structure is completely ironed out.

**Comment by ekinakyurek** [comment]
Data and models in this repo is not used in the layers itself. They are for examples and models implemented by these layers.

**Comment by denizyuret** [comment]
Is IndexedDict or anything else under src/datasets required for Layers to
function?

**Comment by ekinakyurek** [comment]
No it’s not required

-Ekin
________________________________

**Comment by denizyuret** [comment]
I started copying stuff in a Knet PR. I will freeze the current state of
the package as the Knet.Layers20 submodule and try not to break it in
future Knet releases. For further development we can continue on
KnetLayers, add functionality to Knet.Layers20, or start a Knet.Layers21 if
we decide we need breaking changes.

**Pull request merged**
